[2024-01-27 20:36:21,891: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 20:36:21,915: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 20:36:21,917: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 20:36:21,921: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 20:36:22,932: INFO/MainProcess] mingle: all alone
[2024-01-27 20:36:22,952: INFO/MainProcess] celery@545afd071314 ready.
[2024-01-27 21:29:07,242: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 21:29:07,272: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 21:29:07,275: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 21:29:07,279: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 21:29:08,290: INFO/MainProcess] mingle: all alone
[2024-01-27 21:29:08,303: INFO/MainProcess] celery@28918c0815b2 ready.
[2024-01-27 21:59:45,591: INFO/MainProcess] Task maths.tasks.task_sum[0e79ec16-4495-4060-9ffe-53fba9706644] received
[2024-01-27 21:59:46,607: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[0e79ec16-4495-4060-9ffe-53fba9706644] succeeded in 1.0149092210049275s: 3
[2024-01-27 22:02:37,724: INFO/MainProcess] Task maths.tasks.task_sum[b70abe0c-06de-47d8-bdbf-492004f07bb3] received
[2024-01-27 22:02:38,593: INFO/MainProcess] Task maths.tasks.task_sum[585510a5-caf9-4cb5-9c5a-24ea2ed2f266] received
[2024-01-27 22:02:38,727: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[b70abe0c-06de-47d8-bdbf-492004f07bb3] succeeded in 1.0017326889792457s: 3
[2024-01-27 22:02:39,607: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[585510a5-caf9-4cb5-9c5a-24ea2ed2f266] succeeded in 1.011788231000537s: 3
[2024-01-27 22:03:59,110: INFO/MainProcess] Task maths.tasks.task_sum[8f63b556-cc78-4416-a126-72030e4821d5] received
[2024-01-27 22:04:00,112: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[8f63b556-cc78-4416-a126-72030e4821d5] succeeded in 1.0010244260192849s: 3
[2024-01-27 22:04:34,833: INFO/MainProcess] Task maths.tasks.task_sum[ce2af492-ce57-480e-9370-3435fbbeb1ae] received
[2024-01-27 22:04:35,839: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[ce2af492-ce57-480e-9370-3435fbbeb1ae] succeeded in 1.0047858610050753s: 3
[2024-01-27 22:04:57,609: INFO/MainProcess] Task maths.tasks.task_sum[82117724-2786-44d8-a8b1-dd7a432db97d] received
[2024-01-27 22:04:58,612: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[82117724-2786-44d8-a8b1-dd7a432db97d] succeeded in 1.0022113070008345s: 3
[2024-01-27 22:05:18,981: INFO/MainProcess] Task maths.tasks.task_sum[73666e74-119d-4f15-9a50-5516e9f2c347] received
[2024-01-27 22:05:19,983: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[73666e74-119d-4f15-9a50-5516e9f2c347] succeeded in 1.0009260129882023s: 3
[2024-01-27 22:05:49,909: INFO/MainProcess] Task maths.tasks.task_sum[32286092-f90c-4c89-96d4-0e04bc82115a] received
[2024-01-27 22:05:50,911: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[32286092-f90c-4c89-96d4-0e04bc82115a] succeeded in 1.0013404579949565s: 3
[2024-01-27 22:06:28,083: INFO/MainProcess] Task maths.tasks.task_sum[6411852e-7c2b-4115-9712-b0dbe753e8cb] received
[2024-01-27 22:06:29,089: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[6411852e-7c2b-4115-9712-b0dbe753e8cb] succeeded in 1.004521149006905s: 3
[2024-01-27 22:45:48,666: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 22:45:48,677: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 22:45:48,678: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 22:45:48,680: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 22:45:49,690: INFO/MainProcess] mingle: all alone
[2024-01-27 22:45:49,704: INFO/MainProcess] celery@d74fa1475349 ready.
[2024-01-27 22:45:53,360: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-27 22:46:21,002: INFO/MainProcess] Task maths.tasks.task_sum[156e0755-80f2-4382-81a5-ba25020fbb51] received
[2024-01-27 22:46:22,008: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[156e0755-80f2-4382-81a5-ba25020fbb51] succeeded in 1.0032504849950783s: 3
[2024-01-27 22:46:40,426: INFO/MainProcess] Task maths.tasks.task_sum[c6f7d60f-428f-4c2e-b08f-da362ba2075c] received
[2024-01-27 22:46:41,430: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[c6f7d60f-428f-4c2e-b08f-da362ba2075c] succeeded in 1.0011292659910396s: 3
[2024-01-27 22:57:21,402: INFO/MainProcess] Task maths.tasks.task_sum[83a73602-2d6d-4024-9fe1-27bc6f4f865f] received
[2024-01-27 22:57:22,409: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[83a73602-2d6d-4024-9fe1-27bc6f4f865f] succeeded in 1.0050624439900275s: 3
[2024-01-27 23:45:33,817: INFO/MainProcess] Task maths.tasks.task_sum[617a0013-e2e1-4ff5-bb77-c08265fd5a08] received
[2024-01-27 23:45:34,825: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[617a0013-e2e1-4ff5-bb77-c08265fd5a08] succeeded in 1.005599721975159s: 3
[2024-01-27 23:46:13,911: INFO/MainProcess] Task maths.tasks.task_sum[9a7fe6ef-6e62-426c-8a4d-18be314d9193] received
[2024-01-27 23:46:14,918: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[9a7fe6ef-6e62-426c-8a4d-18be314d9193] succeeded in 1.004806090000784s: 3
[2024-01-27 23:46:22,900: INFO/MainProcess] Task maths.tasks.task_sum[c00fa20f-8254-4317-aee1-2995695bdcde] received
[2024-01-27 23:46:23,907: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[c00fa20f-8254-4317-aee1-2995695bdcde] succeeded in 1.004847615986364s: 3
[2024-01-27 23:46:33,545: INFO/MainProcess] Task maths.tasks.task_sum[33a6c21c-9e4e-4936-ba77-55dcc3e34f4c] received
[2024-01-27 23:46:34,547: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[33a6c21c-9e4e-4936-ba77-55dcc3e34f4c] succeeded in 1.0010771930101328s: 3
[2024-01-27 23:47:15,183: INFO/MainProcess] Task maths.tasks.task_sum[793c49d1-c5c6-4b76-bf63-7c9269f7c2fe] received
[2024-01-27 23:47:16,190: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[793c49d1-c5c6-4b76-bf63-7c9269f7c2fe] succeeded in 1.0052512300026137s: 3
[2024-01-27 23:47:28,127: INFO/MainProcess] Task maths.tasks.task_sum[d0c85d57-6032-4249-baa0-45932818c6c9] received
[2024-01-27 23:47:29,132: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[d0c85d57-6032-4249-baa0-45932818c6c9] succeeded in 1.0035733599797823s: 3
[2024-01-27 23:49:44,012: INFO/MainProcess] Task maths.tasks.task_sum[bcdbeb3e-a56c-4b1a-bfc2-052444f6311d] received
[2024-01-27 23:49:44,043: INFO/MainProcess] Task maths.tasks.task_sum[3f82fe88-2869-4b1e-8e0c-cf0c9139ddd5] received
[2024-01-27 23:49:44,101: INFO/MainProcess] Task maths.tasks.task_sum[05ef7308-57af-47d4-8493-1e33d6e2384d] received
[2024-01-27 23:49:44,108: INFO/MainProcess] Task maths.tasks.task_sum[1f244804-2411-4a11-964d-fd1e451b350a] received
[2024-01-27 23:49:44,110: INFO/MainProcess] Task maths.tasks.task_sum[e039f303-c1a8-4dc2-b038-f0d4d1ed6d5c] received
[2024-01-27 23:49:44,166: INFO/MainProcess] Task maths.tasks.task_sum[0558cd2a-4450-48a8-b13a-9db974be26af] received
[2024-01-27 23:49:44,174: INFO/MainProcess] Task maths.tasks.task_sum[e365de57-50cb-4657-99ed-5861b29686db] received
[2024-01-27 23:49:44,182: INFO/MainProcess] Task maths.tasks.task_sum[d589bb44-2828-40d7-a5db-695e94397bba] received
[2024-01-27 23:49:44,192: INFO/MainProcess] Task maths.tasks.task_sum[2ae3795d-3307-4daa-81ff-21b0bbd09e9f] received
[2024-01-27 23:49:44,207: INFO/MainProcess] Task maths.tasks.task_sum[31fcf341-1406-4ff0-ad92-5258b53790f7] received
[2024-01-27 23:49:45,015: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[bcdbeb3e-a56c-4b1a-bfc2-052444f6311d] succeeded in 1.0010079350031447s: 3
[2024-01-27 23:49:45,062: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[3f82fe88-2869-4b1e-8e0c-cf0c9139ddd5] succeeded in 1.0168990209931508s: 3
[2024-01-27 23:49:45,114: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[05ef7308-57af-47d4-8493-1e33d6e2384d] succeeded in 1.0108922679792158s: 3
[2024-01-27 23:49:45,119: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[1f244804-2411-4a11-964d-fd1e451b350a] succeeded in 1.007749717013212s: 3
[2024-01-27 23:49:46,022: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[e039f303-c1a8-4dc2-b038-f0d4d1ed6d5c] succeeded in 1.0053715230023954s: 3
[2024-01-27 23:49:46,078: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[0558cd2a-4450-48a8-b13a-9db974be26af] succeeded in 1.002672504982911s: 3
[2024-01-27 23:49:46,126: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[e365de57-50cb-4657-99ed-5861b29686db] succeeded in 1.006852324004285s: 3
[2024-01-27 23:49:46,128: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[d589bb44-2828-40d7-a5db-695e94397bba] succeeded in 1.004761178017361s: 3
[2024-01-27 23:49:47,040: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[2ae3795d-3307-4daa-81ff-21b0bbd09e9f] succeeded in 1.0062495520105585s: 3
[2024-01-27 23:49:47,088: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[31fcf341-1406-4ff0-ad92-5258b53790f7] succeeded in 1.0069634310202673s: 3
[2024-01-27 23:58:33,142: INFO/MainProcess] Task maths.tasks.task_sum[8b0cfa93-6652-4e78-bdec-2cfe93cdb46d] received
[2024-01-27 23:58:33,158: INFO/MainProcess] Task maths.tasks.task_sum[02e87ac8-fd7e-4e29-8765-2d572942b05c] received
[2024-01-27 23:58:34,149: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[8b0cfa93-6652-4e78-bdec-2cfe93cdb46d] succeeded in 1.0050685169990174s: 3
[2024-01-27 23:58:34,163: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[02e87ac8-fd7e-4e29-8765-2d572942b05c] succeeded in 1.003755017009098s: 3
[2024-01-27 23:59:35,576: INFO/MainProcess] Task maths.tasks.task_sum[b8e935f4-d192-4d16-95ae-e270350b41dd] received
[2024-01-27 23:59:35,599: INFO/MainProcess] Task maths.tasks.task_sum[06d6b044-8fe5-41b5-ada0-9d519d3d1999] received
[2024-01-27 23:59:36,581: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[b8e935f4-d192-4d16-95ae-e270350b41dd] succeeded in 1.0027351040043868s: 3
[2024-01-27 23:59:36,603: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[06d6b044-8fe5-41b5-ada0-9d519d3d1999] succeeded in 1.0019428320229053s: 3
[2024-01-27 23:59:53,359: INFO/MainProcess] Task maths.tasks.task_sum[f25641f1-3b5a-4014-8c77-a4f94f15bd79] received
[2024-01-27 23:59:53,375: INFO/MainProcess] Task maths.tasks.task_sum[e94d850f-b216-46ae-a7fc-13733c6214ab] received
[2024-01-27 23:59:54,362: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[f25641f1-3b5a-4014-8c77-a4f94f15bd79] succeeded in 1.0013444169890136s: 3
[2024-01-27 23:59:54,377: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[e94d850f-b216-46ae-a7fc-13733c6214ab] succeeded in 1.0011645809863694s: 3
[2024-01-28 00:00:35,619: INFO/MainProcess] Task maths.tasks.task_sum[20a334e0-49bf-487c-b224-56a1ebab2e45] received
[2024-01-28 00:00:36,624: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[20a334e0-49bf-487c-b224-56a1ebab2e45] succeeded in 1.0037586760008708s: 3
[2024-01-28 00:01:05,329: INFO/MainProcess] Task maths.tasks.task_sum[060f7a6a-edca-4dc7-a4fa-fa80fadad414] received
[2024-01-28 00:01:06,331: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[060f7a6a-edca-4dc7-a4fa-fa80fadad414] succeeded in 1.00144672501483s: 3
[2024-01-28 00:01:26,803: INFO/MainProcess] Task maths.tasks.task_sum[b1632985-0fbd-4285-a50f-2b27ffcaf444] received
[2024-01-28 00:01:27,812: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[b1632985-0fbd-4285-a50f-2b27ffcaf444] succeeded in 1.0068922599893995s: 3
[2024-01-28 00:01:38,495: INFO/MainProcess] Task maths.tasks.task_sum[f14a1c0c-e9ef-47bc-a5df-d2da3e621bf7] received
[2024-01-28 00:01:39,502: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[f14a1c0c-e9ef-47bc-a5df-d2da3e621bf7] succeeded in 1.0019046319939662s: 3
[2024-01-28 00:01:49,770: INFO/MainProcess] Task maths.tasks.task_sum[8e628377-4b64-442b-a45c-d857d0d49bc9] received
[2024-01-28 00:01:50,778: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[8e628377-4b64-442b-a45c-d857d0d49bc9] succeeded in 1.0060258989979047s: 3
[2024-01-28 00:02:08,769: INFO/MainProcess] Task maths.tasks.task_sum[29835b57-aa0e-4d17-b917-aed2b07dbe03] received
[2024-01-28 00:02:09,775: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[29835b57-aa0e-4d17-b917-aed2b07dbe03] succeeded in 1.005144997005118s: 3
[2024-01-28 00:02:25,805: INFO/MainProcess] Task maths.tasks.task_sum[2e17b234-3324-4a96-8b66-c62edbaf2087] received
[2024-01-28 00:02:26,810: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[2e17b234-3324-4a96-8b66-c62edbaf2087] succeeded in 1.003123916016193s: 3
[2024-01-28 00:02:37,534: INFO/MainProcess] Task maths.tasks.task_sum[253279c8-641d-46be-bb6d-e20f9f25e84b] received
[2024-01-28 00:02:38,538: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[253279c8-641d-46be-bb6d-e20f9f25e84b] succeeded in 1.0025316670071334s: 3
[2024-01-28 00:02:56,236: INFO/MainProcess] Task maths.tasks.task_sum[8c25974e-bd2d-4967-9f7d-68e90403a739] received
[2024-01-28 00:02:57,238: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[8c25974e-bd2d-4967-9f7d-68e90403a739] succeeded in 1.0008245059871115s: 3
[2024-01-28 00:03:10,481: INFO/MainProcess] Task maths.tasks.task_sum[dae94248-78fa-4ad6-8467-e041c524e4c7] received
[2024-01-28 00:03:11,484: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[dae94248-78fa-4ad6-8467-e041c524e4c7] succeeded in 1.0015527889772784s: 12
[2024-01-28 00:08:58,935: INFO/MainProcess] Task maths.tasks.task_sum[2debaf5b-c3d1-470b-b290-59b1e24ab55d] received
[2024-01-28 00:08:59,937: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[2debaf5b-c3d1-470b-b290-59b1e24ab55d] succeeded in 1.0009640200005379s: 12
[2024-01-28 00:09:09,431: INFO/MainProcess] Task maths.tasks.task_sum[a8f6208c-28e4-4526-9f08-28bde52c91f5] received
[2024-01-28 00:09:10,436: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[a8f6208c-28e4-4526-9f08-28bde52c91f5] succeeded in 1.0011709489917848s: 12
[2024-01-28 00:10:58,649: INFO/MainProcess] Task maths.tasks.task_sum[839d7453-ff97-4676-a3b9-a37a758f0a52] received
[2024-01-28 00:10:59,653: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[839d7453-ff97-4676-a3b9-a37a758f0a52] succeeded in 1.0010933759913314s: 12
[2024-01-28 00:11:16,757: INFO/MainProcess] Task maths.tasks.task_sum[ab7eb081-371c-43b5-aa77-6d548ad5ed35] received
[2024-01-28 00:11:17,763: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[ab7eb081-371c-43b5-aa77-6d548ad5ed35] succeeded in 1.001101382978959s: 12
[2024-01-28 00:12:46,575: INFO/MainProcess] Task maths.tasks.task_sum[b9091e80-e7a3-4c45-b861-3b26d44bf264] received
[2024-01-28 00:12:46,656: INFO/MainProcess] Task maths.tasks.task_sum[f4e5235c-d1bd-41ce-ba90-ca7326766592] received
[2024-01-28 00:12:46,751: INFO/MainProcess] Task maths.tasks.task_sum[cdf28d8d-9f7f-4f58-9b94-7452624d2a0d] received
[2024-01-28 00:12:46,761: INFO/MainProcess] Task maths.tasks.task_sum[4dfee80f-d18f-4fe2-a912-c33953f73c30] received
[2024-01-28 00:12:46,765: INFO/MainProcess] Task maths.tasks.task_sum[d1bfae6f-92a7-4a96-a9d2-4d32e4cbd932] received
[2024-01-28 00:12:46,768: INFO/MainProcess] Task maths.tasks.task_sum[2912d074-25d4-4214-9999-c2bfa96f1dd0] received
[2024-01-28 00:12:46,798: INFO/MainProcess] Task maths.tasks.task_sum[3c7b884f-f761-4866-8f85-92230fd28c98] received
[2024-01-28 00:12:46,802: INFO/MainProcess] Task maths.tasks.task_sum[96700bfd-fe44-4ece-8094-99c18d692424] received
[2024-01-28 00:12:46,815: INFO/MainProcess] Task maths.tasks.task_sum[fa2b2dbe-4fc5-41f3-96d4-578d7100e9c2] received
[2024-01-28 00:12:46,827: INFO/MainProcess] Task maths.tasks.task_sum[f865c94f-4036-4310-8fea-8deb260c228d] received
[2024-01-28 00:12:47,578: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[b9091e80-e7a3-4c45-b861-3b26d44bf264] succeeded in 1.0010167850123253s: 12
[2024-01-28 00:12:47,662: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[f4e5235c-d1bd-41ce-ba90-ca7326766592] succeeded in 1.0031139269995037s: 12
[2024-01-28 00:12:47,755: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[cdf28d8d-9f7f-4f58-9b94-7452624d2a0d] succeeded in 1.00155032298062s: 12
[2024-01-28 00:12:47,770: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[4dfee80f-d18f-4fe2-a912-c33953f73c30] succeeded in 1.0066647639905568s: 12
[2024-01-28 00:12:48,583: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[d1bfae6f-92a7-4a96-a9d2-4d32e4cbd932] succeeded in 1.0010215900256298s: 12
[2024-01-28 00:12:48,668: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[2912d074-25d4-4214-9999-c2bfa96f1dd0] succeeded in 1.0015677500050515s: 12
[2024-01-28 00:12:48,760: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[3c7b884f-f761-4866-8f85-92230fd28c98] succeeded in 1.0011946739978157s: 12
[2024-01-28 00:12:48,775: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[96700bfd-fe44-4ece-8094-99c18d692424] succeeded in 1.0018168310052715s: 12
[2024-01-28 00:12:49,587: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[fa2b2dbe-4fc5-41f3-96d4-578d7100e9c2] succeeded in 1.0012368930038065s: 12
[2024-01-28 00:12:49,673: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[f865c94f-4036-4310-8fea-8deb260c228d] succeeded in 1.001201871986268s: 12
[2024-01-28 00:12:55,172: INFO/MainProcess] Task maths.tasks.task_sum[5c1e365a-a516-49ef-a4a0-2c5bdef8bb0c] received
[2024-01-28 00:12:55,283: INFO/MainProcess] Task maths.tasks.task_sum[30945998-393a-485a-a23e-7aa29d8f47ed] received
[2024-01-28 00:12:55,324: INFO/MainProcess] Task maths.tasks.task_sum[2034e40d-702a-481f-bc3a-a10e8b5e5f5d] received
[2024-01-28 00:12:55,334: INFO/MainProcess] Task maths.tasks.task_sum[b461166d-91d4-4bd6-8b09-b5fd1ed8748f] received
[2024-01-28 00:12:55,364: INFO/MainProcess] Task maths.tasks.task_sum[4abc99a0-d4d9-477a-b2df-444e24b18a37] received
[2024-01-28 00:12:55,372: INFO/MainProcess] Task maths.tasks.task_sum[db43b8bc-7dc0-47cd-925f-4f153819c91e] received
[2024-01-28 00:12:55,373: INFO/MainProcess] Task maths.tasks.task_sum[5efff1f5-68ba-4254-8061-a203d459d3af] received
[2024-01-28 00:12:55,377: INFO/MainProcess] Task maths.tasks.task_sum[265c3606-82cf-41a3-8cec-bf0b4970a47c] received
[2024-01-28 00:12:55,384: INFO/MainProcess] Task maths.tasks.task_sum[1634f8e9-dc3b-492a-87c0-c53b6d10768b] received
[2024-01-28 00:12:55,397: INFO/MainProcess] Task maths.tasks.task_sum[46448460-1b15-4085-9659-2968c4dc2fd1] received
[2024-01-28 00:12:56,178: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[5c1e365a-a516-49ef-a4a0-2c5bdef8bb0c] succeeded in 1.0022984420065768s: 12
[2024-01-28 00:12:56,286: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[30945998-393a-485a-a23e-7aa29d8f47ed] succeeded in 1.0011639629956335s: 12
[2024-01-28 00:12:56,332: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[2034e40d-702a-481f-bc3a-a10e8b5e5f5d] succeeded in 1.0016600980015937s: 12
[2024-01-28 00:12:56,341: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[b461166d-91d4-4bd6-8b09-b5fd1ed8748f] succeeded in 1.0010111790033989s: 12
[2024-01-28 00:12:57,184: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[4abc99a0-d4d9-477a-b2df-444e24b18a37] succeeded in 1.0017979539989028s: 12
[2024-01-28 00:12:57,290: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[db43b8bc-7dc0-47cd-925f-4f153819c91e] succeeded in 1.0012753779883496s: 12
[2024-01-28 00:12:57,335: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[5efff1f5-68ba-4254-8061-a203d459d3af] succeeded in 1.0014452360046562s: 12
[2024-01-28 00:12:57,353: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[265c3606-82cf-41a3-8cec-bf0b4970a47c] succeeded in 1.0030810000025667s: 12
[2024-01-28 00:12:58,187: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[1634f8e9-dc3b-492a-87c0-c53b6d10768b] succeeded in 1.0009489379881416s: 12
[2024-01-28 00:12:58,293: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[46448460-1b15-4085-9659-2968c4dc2fd1] succeeded in 1.0013378639996517s: 12
[2024-01-28 00:13:03,856: INFO/MainProcess] Task maths.tasks.task_sum[4625fb15-ff95-4555-a2ac-e018e6d0c288] received
[2024-01-28 00:13:03,882: INFO/MainProcess] Task maths.tasks.task_sum[722f9e35-7ce6-4518-90a7-de740f313713] received
[2024-01-28 00:13:03,957: INFO/MainProcess] Task maths.tasks.task_sum[e84c7146-001a-41c9-a89c-17e80cea247f] received
[2024-01-28 00:13:03,971: INFO/MainProcess] Task maths.tasks.task_sum[d64dc7b4-d00d-4a9d-ab17-0759227bcd05] received
[2024-01-28 00:13:03,977: INFO/MainProcess] Task maths.tasks.task_sum[c23ab671-cf7f-423a-a775-4ea131768b15] received
[2024-01-28 00:13:03,984: INFO/MainProcess] Task maths.tasks.task_sum[5f2ecc82-65bd-4eaf-9c59-07676c319694] received
[2024-01-28 00:13:03,993: INFO/MainProcess] Task maths.tasks.task_sum[edd136da-d21e-420f-9e14-fc9ecb375d76] received
[2024-01-28 00:13:04,000: INFO/MainProcess] Task maths.tasks.task_sum[33deacc7-3e82-4e47-8401-8872fedf0a92] received
[2024-01-28 00:13:04,024: INFO/MainProcess] Task maths.tasks.task_sum[cae8d319-fb21-4600-92c1-51d4d11bd003] received
[2024-01-28 00:13:04,055: INFO/MainProcess] Task maths.tasks.task_sum[e458694e-d62c-49bc-86e9-a19aff8ca6bb] received
[2024-01-28 00:13:04,861: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[4625fb15-ff95-4555-a2ac-e018e6d0c288] succeeded in 1.0013958119961899s: 12
[2024-01-28 00:13:04,888: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[722f9e35-7ce6-4518-90a7-de740f313713] succeeded in 1.0034250449971296s: 12
[2024-01-28 00:13:04,960: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[e84c7146-001a-41c9-a89c-17e80cea247f] succeeded in 1.001475360011682s: 12
[2024-01-28 00:13:04,974: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[d64dc7b4-d00d-4a9d-ab17-0759227bcd05] succeeded in 1.0010841680050362s: 12
[2024-01-28 00:13:05,873: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[c23ab671-cf7f-423a-a775-4ea131768b15] succeeded in 1.000801694986876s: 12
[2024-01-28 00:13:05,892: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[5f2ecc82-65bd-4eaf-9c59-07676c319694] succeeded in 1.0029642879962921s: 12
[2024-01-28 00:13:05,964: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[edd136da-d21e-420f-9e14-fc9ecb375d76] succeeded in 1.001798225013772s: 12
[2024-01-28 00:13:05,979: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[33deacc7-3e82-4e47-8401-8872fedf0a92] succeeded in 1.0010331280063838s: 12
[2024-01-28 00:13:06,876: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[cae8d319-fb21-4600-92c1-51d4d11bd003] succeeded in 1.0012679299979936s: 12
[2024-01-28 00:13:06,897: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[e458694e-d62c-49bc-86e9-a19aff8ca6bb] succeeded in 1.0010621379769873s: 12
[2024-01-28 00:13:58,259: INFO/MainProcess] Task maths.tasks.task_sum[7c7cd267-390b-4304-8795-edda49d9f018] received
[2024-01-28 00:13:58,369: INFO/MainProcess] Task maths.tasks.task_sum[40e7f7df-f335-4eb9-acc2-a5f8e1375550] received
[2024-01-28 00:13:58,417: INFO/MainProcess] Task maths.tasks.task_sum[9ad971e4-1491-4016-9e01-8c553ee15aff] received
[2024-01-28 00:13:58,420: INFO/MainProcess] Task maths.tasks.task_sum[a84f6cf7-c158-401f-af86-d0a5cb51e941] received
[2024-01-28 00:13:58,429: INFO/MainProcess] Task maths.tasks.task_sum[d8d97141-d515-4e7d-bd45-43542fd6fc92] received
[2024-01-28 00:13:58,441: INFO/MainProcess] Task maths.tasks.task_sum[ac846d3a-d6df-4f74-bba5-e7686eaf58e2] received
[2024-01-28 00:13:58,465: INFO/MainProcess] Task maths.tasks.task_sum[1416ad5e-7343-4e8d-b99c-d13ee94d7c44] received
[2024-01-28 00:13:58,482: INFO/MainProcess] Task maths.tasks.task_sum[60649620-6663-4eab-b833-5551948a7f60] received
[2024-01-28 00:13:58,499: INFO/MainProcess] Task maths.tasks.task_sum[33b3a169-154c-4c87-b4ee-e81e0dce341f] received
[2024-01-28 00:13:58,525: INFO/MainProcess] Task maths.tasks.task_sum[f6a87736-797b-4d56-a116-8f254496cd0c] received
[2024-01-28 00:13:59,266: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[7c7cd267-390b-4304-8795-edda49d9f018] succeeded in 1.0047810940013733s: 12
[2024-01-28 00:13:59,372: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[40e7f7df-f335-4eb9-acc2-a5f8e1375550] succeeded in 1.0008993350202218s: 12
[2024-01-28 00:13:59,424: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[9ad971e4-1491-4016-9e01-8c553ee15aff] succeeded in 1.0049457109998912s: 12
[2024-01-28 00:13:59,428: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[a84f6cf7-c158-401f-af86-d0a5cb51e941] succeeded in 1.005407960008597s: 12
[2024-01-28 00:14:00,286: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[d8d97141-d515-4e7d-bd45-43542fd6fc92] succeeded in 1.0061226960096974s: 12
[2024-01-28 00:14:00,381: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[ac846d3a-d6df-4f74-bba5-e7686eaf58e2] succeeded in 1.0068051670095883s: 12
[2024-01-28 00:14:00,438: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[1416ad5e-7343-4e8d-b99c-d13ee94d7c44] succeeded in 1.0025683889980428s: 12
[2024-01-28 00:14:00,438: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[60649620-6663-4eab-b833-5551948a7f60] succeeded in 1.002224160998594s: 12
[2024-01-28 00:14:01,303: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[33b3a169-154c-4c87-b4ee-e81e0dce341f] succeeded in 1.0052252809982747s: 12
[2024-01-28 00:14:01,393: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[f6a87736-797b-4d56-a116-8f254496cd0c] succeeded in 1.0063700069731567s: 12
[2024-01-28 00:14:12,534: INFO/MainProcess] Task maths.tasks.task_sum[9a386d26-7bfe-4888-bea7-60b85c12edce] received
[2024-01-28 00:14:12,599: INFO/MainProcess] Task maths.tasks.task_sum[ad83f3e3-03a8-421d-acac-4e8ddceca20d] received
[2024-01-28 00:14:12,704: INFO/MainProcess] Task maths.tasks.task_sum[fb7d8f7f-b6c4-4e5d-b57f-4531c42a6be5] received
[2024-01-28 00:14:12,732: INFO/MainProcess] Task maths.tasks.task_sum[8df4e729-ed4d-4261-bff7-d022cb16a808] received
[2024-01-28 00:14:12,772: INFO/MainProcess] Task maths.tasks.task_sum[68883343-2e00-4610-ac4e-df89c91bc4e0] received
[2024-01-28 00:14:12,802: INFO/MainProcess] Task maths.tasks.task_sum[20a7e5d3-b2df-425c-bb3d-023171f8c4b0] received
[2024-01-28 00:14:12,806: INFO/MainProcess] Task maths.tasks.task_sum[75854c29-0e06-49e9-8291-f6d0b4724904] received
[2024-01-28 00:14:12,847: INFO/MainProcess] Task maths.tasks.task_sum[eb83f22a-58af-4c50-9349-002df84faf41] received
[2024-01-28 00:14:12,898: INFO/MainProcess] Task maths.tasks.task_sum[a7d0f993-c370-404a-b61d-3a1ba8c1007a] received
[2024-01-28 00:14:12,946: INFO/MainProcess] Task maths.tasks.task_sum[07c1fbd9-ef89-4e6a-b9e5-4e4f456764c1] received
[2024-01-28 00:14:12,977: INFO/MainProcess] Task maths.tasks.task_sum[ffec76f8-190c-4977-bb03-9ce716289269] received
[2024-01-28 00:14:12,984: INFO/MainProcess] Task maths.tasks.task_sum[cc0d64d4-4bac-44e7-a844-bca45121ef96] received
[2024-01-28 00:14:13,001: INFO/MainProcess] Task maths.tasks.task_sum[8ae5324d-bbda-4d9d-aa9c-3438a9484c99] received
[2024-01-28 00:14:13,027: INFO/MainProcess] Task maths.tasks.task_sum[169c0656-f663-4800-985b-b364040dfd45] received
[2024-01-28 00:14:13,166: INFO/MainProcess] Task maths.tasks.task_sum[0727e7e4-45dd-472a-bf41-36527ca99d2e] received
[2024-01-28 00:14:13,193: INFO/MainProcess] Task maths.tasks.task_sum[8678af3d-b3ac-4a8e-8cea-ead0c4308ec4] received
[2024-01-28 00:14:13,196: INFO/MainProcess] Task maths.tasks.task_sum[6cbd9d56-9e88-49d3-8de1-0dae48a51d84] received
[2024-01-28 00:14:13,234: INFO/MainProcess] Task maths.tasks.task_sum[82301aca-f517-4f92-ab5e-801299b2f6da] received
[2024-01-28 00:14:13,238: INFO/MainProcess] Task maths.tasks.task_sum[092821bf-1751-4018-ab08-e236d2dd7b8e] received
[2024-01-28 00:14:13,244: INFO/MainProcess] Task maths.tasks.task_sum[d6a49829-038a-40cc-a7ed-2a3389c1045a] received
[2024-01-28 00:14:13,540: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[9a386d26-7bfe-4888-bea7-60b85c12edce] succeeded in 1.001176835008664s: 12
[2024-01-28 00:14:13,546: INFO/MainProcess] Task maths.tasks.task_sum[a72493f5-dfaf-452f-b94c-27ac596b3da8] received
[2024-01-28 00:14:13,607: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[ad83f3e3-03a8-421d-acac-4e8ddceca20d] succeeded in 1.0011578839912545s: 12
[2024-01-28 00:14:13,613: INFO/MainProcess] Task maths.tasks.task_sum[eb42ba45-dfbd-43b0-9bfc-0cf8e461ae86] received
[2024-01-28 00:14:13,744: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[8df4e729-ed4d-4261-bff7-d022cb16a808] succeeded in 1.0081543639826123s: 12
[2024-01-28 00:14:13,745: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[fb7d8f7f-b6c4-4e5d-b57f-4531c42a6be5] succeeded in 1.0087777240260039s: 12
[2024-01-28 00:14:13,768: INFO/MainProcess] Task maths.tasks.task_sum[b6f8a810-2437-4b6e-ba1b-a270d2d8b6ff] received
[2024-01-28 00:14:13,772: INFO/MainProcess] Task maths.tasks.task_sum[b7e770ec-8a68-4605-a49e-ea5c216d739f] received
[2024-01-28 00:14:14,544: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[68883343-2e00-4610-ac4e-df89c91bc4e0] succeeded in 1.0017089869943447s: 12
[2024-01-28 00:14:14,551: INFO/MainProcess] Task maths.tasks.task_sum[3999d7ed-3b7c-471c-a88a-b0cfe8926187] received
[2024-01-28 00:14:14,612: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[20a7e5d3-b2df-425c-bb3d-023171f8c4b0] succeeded in 1.0032631520007271s: 12
[2024-01-28 00:14:14,619: INFO/MainProcess] Task maths.tasks.task_sum[43f0aa62-f614-41fa-9f9b-bfa85f4ff504] received
[2024-01-28 00:14:14,755: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[eb83f22a-58af-4c50-9349-002df84faf41] succeeded in 1.0012416579993442s: 12
[2024-01-28 00:14:14,760: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[75854c29-0e06-49e9-8291-f6d0b4724904] succeeded in 1.0084287899953779s: 12
[2024-01-28 00:14:14,761: INFO/MainProcess] Task maths.tasks.task_sum[a9f30b69-4402-4020-aeb6-dea316071b11] received
[2024-01-28 00:14:14,766: INFO/MainProcess] Task maths.tasks.task_sum[cd1b3f19-9a6f-449e-ae8c-69ed5b6ab177] received
[2024-01-28 00:14:15,549: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[a7d0f993-c370-404a-b61d-3a1ba8c1007a] succeeded in 1.0009330640023109s: 12
[2024-01-28 00:14:15,555: INFO/MainProcess] Task maths.tasks.task_sum[38142c8f-3dbf-4454-aa61-307b0defea8e] received
[2024-01-28 00:14:15,615: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[07c1fbd9-ef89-4e6a-b9e5-4e4f456764c1] succeeded in 1.0009707559947856s: 12
[2024-01-28 00:14:15,622: INFO/MainProcess] Task maths.tasks.task_sum[fb156181-e31f-4d3f-b0f3-9b467f3ed104] received
[2024-01-28 00:14:15,759: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[ffec76f8-190c-4977-bb03-9ce716289269] succeeded in 1.001070440019248s: 12
[2024-01-28 00:14:15,763: INFO/MainProcess] Task maths.tasks.task_sum[a7be3844-27f4-4537-b76f-d3acba51f956] received
[2024-01-28 00:14:15,764: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[cc0d64d4-4bac-44e7-a844-bca45121ef96] succeeded in 1.0009007100015879s: 12
[2024-01-28 00:14:15,771: INFO/MainProcess] Task maths.tasks.task_sum[6c47aa2b-416b-4ac5-a2b5-bdd1799ef6ae] received
[2024-01-28 00:14:16,555: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[8ae5324d-bbda-4d9d-aa9c-3438a9484c99] succeeded in 1.0039245120133273s: 12
[2024-01-28 00:14:16,563: INFO/MainProcess] Task maths.tasks.task_sum[59a894a4-e54a-4dbb-989e-6f386128b343] received
[2024-01-28 00:14:16,619: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[169c0656-f663-4800-985b-b364040dfd45] succeeded in 1.0010581980168354s: 12
[2024-01-28 00:14:16,623: INFO/MainProcess] Task maths.tasks.task_sum[a8aa5c65-fffd-4e73-80e5-d9575c37f675] received
[2024-01-28 00:14:16,761: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[0727e7e4-45dd-472a-bf41-36527ca99d2e] succeeded in 1.000918031000765s: 12
[2024-01-28 00:14:16,766: INFO/MainProcess] Task maths.tasks.task_sum[4482bd37-4da7-4456-a9b7-4e60df3a1658] received
[2024-01-28 00:14:16,767: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[8678af3d-b3ac-4a8e-8cea-ead0c4308ec4] succeeded in 1.0012098860170227s: 12
[2024-01-28 00:14:16,774: INFO/MainProcess] Task maths.tasks.task_sum[f323008c-66b4-4cb4-bc82-1ef25a4cb5dc] received
[2024-01-28 00:14:17,562: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[6cbd9d56-9e88-49d3-8de1-0dae48a51d84] succeeded in 1.0010567620047368s: 12
[2024-01-28 00:14:17,566: INFO/MainProcess] Task maths.tasks.task_sum[b78e963d-93ee-4f1d-b9ad-307b3d0c64df] received
[2024-01-28 00:14:17,622: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[82301aca-f517-4f92-ab5e-801299b2f6da] succeeded in 1.0011025559797417s: 12
[2024-01-28 00:14:17,627: INFO/MainProcess] Task maths.tasks.task_sum[b1ed84e8-2e57-484c-9862-f55162639413] received
[2024-01-28 00:14:17,765: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[092821bf-1751-4018-ab08-e236d2dd7b8e] succeeded in 1.0018179249891546s: 12
[2024-01-28 00:14:17,771: INFO/MainProcess] Task maths.tasks.task_sum[7296f638-9c03-405b-9121-0eb568d406d0] received
[2024-01-28 00:14:17,772: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[d6a49829-038a-40cc-a7ed-2a3389c1045a] succeeded in 1.001536866009701s: 12
[2024-01-28 00:14:17,780: INFO/MainProcess] Task maths.tasks.task_sum[3bc76a33-e637-4837-805b-7101ec5144c9] received
[2024-01-28 00:14:18,566: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[a72493f5-dfaf-452f-b94c-27ac596b3da8] succeeded in 1.0016965529939625s: 12
[2024-01-28 00:14:18,571: INFO/MainProcess] Task maths.tasks.task_sum[ab214010-cd34-43e1-ab8a-42c6ace7d9b4] received
[2024-01-28 00:14:18,626: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[eb42ba45-dfbd-43b0-9bfc-0cf8e461ae86] succeeded in 1.0023905230045784s: 12
[2024-01-28 00:14:18,632: INFO/MainProcess] Task maths.tasks.task_sum[66585ad8-7f4c-441e-8464-8756ac3fa82b] received
[2024-01-28 00:14:18,772: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[b6f8a810-2437-4b6e-ba1b-a270d2d8b6ff] succeeded in 1.004154979978921s: 12
[2024-01-28 00:14:18,778: INFO/MainProcess] Task maths.tasks.task_sum[f2b0a591-7521-47a1-838e-3355561ce58b] received
[2024-01-28 00:14:18,779: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[b7e770ec-8a68-4605-a49e-ea5c216d739f] succeeded in 1.0018805029976647s: 12
[2024-01-28 00:14:18,785: INFO/MainProcess] Task maths.tasks.task_sum[ade4ab96-f543-47a5-b557-83322985b536] received
[2024-01-28 00:14:19,571: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[3999d7ed-3b7c-471c-a88a-b0cfe8926187] succeeded in 1.0030509720090777s: 12
[2024-01-28 00:14:19,578: INFO/MainProcess] Task maths.tasks.task_sum[827edc77-b754-4a94-8d7f-7d1129672742] received
[2024-01-28 00:14:19,630: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[43f0aa62-f614-41fa-9f9b-bfa85f4ff504] succeeded in 1.0011391619918868s: 12
[2024-01-28 00:14:19,636: INFO/MainProcess] Task maths.tasks.task_sum[b3e4d14f-bf7e-4b49-bf11-d4d8ab683064] received
[2024-01-28 00:14:19,775: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[a9f30b69-4402-4020-aeb6-dea316071b11] succeeded in 1.0011199550062884s: 12
[2024-01-28 00:14:19,782: INFO/MainProcess] Task maths.tasks.task_sum[d8731d90-a986-4ebc-b298-2cd1fd9f25bc] received
[2024-01-28 00:14:19,782: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[cd1b3f19-9a6f-449e-ae8c-69ed5b6ab177] succeeded in 1.0011665020138025s: 12
[2024-01-28 00:14:19,789: INFO/MainProcess] Task maths.tasks.task_sum[83adcc3f-a306-4510-bb96-e32307c1a36d] received
[2024-01-28 00:14:20,576: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[38142c8f-3dbf-4454-aa61-307b0defea8e] succeeded in 1.001196536992211s: 12
[2024-01-28 00:14:20,582: INFO/MainProcess] Task maths.tasks.task_sum[4ba2b4d4-97ae-4e15-b8f6-595c06a0b35e] received
[2024-01-28 00:14:20,634: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[fb156181-e31f-4d3f-b0f3-9b467f3ed104] succeeded in 1.0010834979766514s: 12
[2024-01-28 00:14:20,638: INFO/MainProcess] Task maths.tasks.task_sum[663a2a1b-5db9-4acc-ae77-1448d85109b2] received
[2024-01-28 00:14:20,779: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[a7be3844-27f4-4537-b76f-d3acba51f956] succeeded in 1.0014454319898505s: 12
[2024-01-28 00:14:20,786: INFO/MainProcess] Task maths.tasks.task_sum[50cb3ff3-2cd9-421a-8116-33f982506453] received
[2024-01-28 00:14:20,787: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[6c47aa2b-416b-4ac5-a2b5-bdd1799ef6ae] succeeded in 1.0010021250054706s: 12
[2024-01-28 00:14:20,796: INFO/MainProcess] Task maths.tasks.task_sum[8f4a8e6c-dbb3-4233-b7e0-46a09d679550] received
[2024-01-28 00:14:21,581: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[59a894a4-e54a-4dbb-989e-6f386128b343] succeeded in 1.0009243940003216s: 12
[2024-01-28 00:14:21,587: INFO/MainProcess] Task maths.tasks.task_sum[9133f628-5304-4bad-9aab-80791952d1f4] received
[2024-01-28 00:14:21,637: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[a8aa5c65-fffd-4e73-80e5-d9575c37f675] succeeded in 1.0010383089829702s: 12
[2024-01-28 00:14:21,654: INFO/MainProcess] Task maths.tasks.task_sum[d4383481-91f5-411f-ba14-4b6634d33a7c] received
[2024-01-28 00:14:21,783: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[4482bd37-4da7-4456-a9b7-4e60df3a1658] succeeded in 1.0012418830010574s: 12
[2024-01-28 00:14:21,790: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[f323008c-66b4-4cb4-bc82-1ef25a4cb5dc] succeeded in 1.0014952539931983s: 12
[2024-01-28 00:14:21,799: INFO/MainProcess] Task maths.tasks.task_sum[99dab034-0455-4413-a8df-925c36c4e21a] received
[2024-01-28 00:14:21,805: INFO/MainProcess] Task maths.tasks.task_sum[4b521d6b-87cd-468d-b8f2-63f2d9b4670c] received
[2024-01-28 00:14:22,584: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[b78e963d-93ee-4f1d-b9ad-307b3d0c64df] succeeded in 1.0013534750032704s: 12
[2024-01-28 00:14:22,591: INFO/MainProcess] Task maths.tasks.task_sum[1230d169-2f46-4e32-b0c7-eb093ffc0645] received
[2024-01-28 00:14:22,645: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[b1ed84e8-2e57-484c-9862-f55162639413] succeeded in 1.0055679959768895s: 12
[2024-01-28 00:14:22,652: INFO/MainProcess] Task maths.tasks.task_sum[e1844297-4113-41a2-9209-8fe95838c6ab] received
[2024-01-28 00:14:22,794: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[7296f638-9c03-405b-9121-0eb568d406d0] succeeded in 1.0022209569870029s: 12
[2024-01-28 00:14:22,794: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[3bc76a33-e637-4837-805b-7101ec5144c9] succeeded in 1.0022153450117912s: 12
[2024-01-28 00:14:22,806: INFO/MainProcess] Task maths.tasks.task_sum[3b4c4edc-0189-4342-a649-6715732b8cbe] received
[2024-01-28 00:14:22,813: INFO/MainProcess] Task maths.tasks.task_sum[0e95fe38-ca4f-4259-a6d3-07bc70e51b7a] received
[2024-01-28 00:14:23,587: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[ab214010-cd34-43e1-ab8a-42c6ace7d9b4] succeeded in 1.0009782139968593s: 12
[2024-01-28 00:14:23,591: INFO/MainProcess] Task maths.tasks.task_sum[c6a3c3fd-7da6-413d-b1e4-69c7690a5d8e] received
[2024-01-28 00:14:23,650: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[66585ad8-7f4c-441e-8464-8756ac3fa82b] succeeded in 1.0012885719770566s: 12
[2024-01-28 00:14:23,656: INFO/MainProcess] Task maths.tasks.task_sum[90875ea7-ffbb-44e0-ac10-571801ea0e41] received
[2024-01-28 00:14:23,799: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[ade4ab96-f543-47a5-b557-83322985b536] succeeded in 1.0014139309932943s: 12
[2024-01-28 00:14:23,801: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[f2b0a591-7521-47a1-838e-3355561ce58b] succeeded in 1.004104269988602s: 12
[2024-01-28 00:14:23,808: INFO/MainProcess] Task maths.tasks.task_sum[4ea0ff30-7f3d-4528-b024-dfd98ead73ba] received
[2024-01-28 00:14:23,814: INFO/MainProcess] Task maths.tasks.task_sum[8656febd-4662-4f9f-8d80-56b604e6144a] received
[2024-01-28 00:14:24,590: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[827edc77-b754-4a94-8d7f-7d1129672742] succeeded in 1.0009813969954848s: 12
[2024-01-28 00:14:24,595: INFO/MainProcess] Task maths.tasks.task_sum[0c97c98f-f01a-4445-aa18-21e88e628971] received
[2024-01-28 00:14:24,655: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[b3e4d14f-bf7e-4b49-bf11-d4d8ab683064] succeeded in 1.0014870860031806s: 12
[2024-01-28 00:14:24,664: INFO/MainProcess] Task maths.tasks.task_sum[9410768c-d257-49e4-85e8-bf3448ec16ce] received
[2024-01-28 00:14:24,805: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[d8731d90-a986-4ebc-b298-2cd1fd9f25bc] succeeded in 1.001126204006141s: 12
[2024-01-28 00:14:24,805: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[83adcc3f-a306-4510-bb96-e32307c1a36d] succeeded in 1.0010418609890621s: 12
[2024-01-28 00:14:24,813: INFO/MainProcess] Task maths.tasks.task_sum[6ef60e7f-4e64-4370-98eb-7819c845d93c] received
[2024-01-28 00:14:24,816: INFO/MainProcess] Task maths.tasks.task_sum[bd86888f-c17d-4b24-9913-119306f2f120] received
[2024-01-28 00:14:25,593: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[4ba2b4d4-97ae-4e15-b8f6-595c06a0b35e] succeeded in 1.0009245359979104s: 12
[2024-01-28 00:14:25,600: INFO/MainProcess] Task maths.tasks.task_sum[17349874-3969-41aa-a88e-de33ae28025d] received
[2024-01-28 00:14:25,659: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[663a2a1b-5db9-4acc-ae77-1448d85109b2] succeeded in 1.001466387999244s: 12
[2024-01-28 00:14:25,668: INFO/MainProcess] Task maths.tasks.task_sum[f8ede4b6-ccc7-4cf9-8580-53a6ba8c3b99] received
[2024-01-28 00:14:25,809: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[50cb3ff3-2cd9-421a-8116-33f982506453] succeeded in 1.0011925139988307s: 12
[2024-01-28 00:14:25,813: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[8f4a8e6c-dbb3-4233-b7e0-46a09d679550] succeeded in 1.0041639640112408s: 12
[2024-01-28 00:14:25,816: INFO/MainProcess] Task maths.tasks.task_sum[6472f0a9-6504-4199-81b6-332075345a7a] received
[2024-01-28 00:14:25,826: INFO/MainProcess] Task maths.tasks.task_sum[ee20583f-25f6-4401-a750-404ca46bf722] received
[2024-01-28 00:14:26,598: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[9133f628-5304-4bad-9aab-80791952d1f4] succeeded in 1.001057290006429s: 12
[2024-01-28 00:14:26,607: INFO/MainProcess] Task maths.tasks.task_sum[15829dce-ba0b-4587-8497-d04320273f54] received
[2024-01-28 00:14:26,667: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[d4383481-91f5-411f-ba14-4b6634d33a7c] succeeded in 1.001692036021268s: 12
[2024-01-28 00:14:26,671: INFO/MainProcess] Task maths.tasks.task_sum[bd10892a-4e26-42e6-bd05-bbfa4f237419] received
[2024-01-28 00:14:26,814: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[99dab034-0455-4413-a8df-925c36c4e21a] succeeded in 1.0022101340000518s: 12
[2024-01-28 00:14:26,822: INFO/MainProcess] Task maths.tasks.task_sum[9101357c-e2b5-4705-8dfe-3b012471604b] received
[2024-01-28 00:14:26,823: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[4b521d6b-87cd-468d-b8f2-63f2d9b4670c] succeeded in 1.001259734010091s: 12
[2024-01-28 00:14:26,833: INFO/MainProcess] Task maths.tasks.task_sum[9b943ba8-0511-400c-bd64-41814925b5a7] received
[2024-01-28 00:14:27,603: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[1230d169-2f46-4e32-b0c7-eb093ffc0645] succeeded in 1.0013449550024234s: 12
[2024-01-28 00:14:27,609: INFO/MainProcess] Task maths.tasks.task_sum[c4379c4a-4c38-43fb-b092-23e8e7eb58df] received
[2024-01-28 00:14:27,670: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[e1844297-4113-41a2-9209-8fe95838c6ab] succeeded in 1.0011456520005595s: 12
[2024-01-28 00:14:27,675: INFO/MainProcess] Task maths.tasks.task_sum[85bf4870-17ad-496e-b89b-a1404f49b2dc] received
[2024-01-28 00:14:27,820: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[3b4c4edc-0189-4342-a649-6715732b8cbe] succeeded in 1.0014728020178154s: 12
[2024-01-28 00:14:27,826: INFO/MainProcess] Task maths.tasks.task_sum[bab665bf-c772-4366-a361-eef9f0dab668] received
[2024-01-28 00:14:27,828: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[0e95fe38-ca4f-4259-a6d3-07bc70e51b7a] succeeded in 1.0010612590122037s: 12
[2024-01-28 00:14:27,836: INFO/MainProcess] Task maths.tasks.task_sum[199adb6d-ab31-43c8-b40c-ef4c30c36b8c] received
[2024-01-28 00:14:28,607: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[c6a3c3fd-7da6-413d-b1e4-69c7690a5d8e] succeeded in 1.0016166430141311s: 12
[2024-01-28 00:14:28,614: INFO/MainProcess] Task maths.tasks.task_sum[86c47ba2-35bd-4eb0-b66c-2a6d993b0f3d] received
[2024-01-28 00:14:28,678: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[90875ea7-ffbb-44e0-ac10-571801ea0e41] succeeded in 1.0053779739828315s: 12
[2024-01-28 00:14:28,707: INFO/MainProcess] Task maths.tasks.task_sum[6e9e904b-f67b-4d3e-8b72-1ae70f3d1ebe] received
[2024-01-28 00:14:28,825: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[4ea0ff30-7f3d-4528-b024-dfd98ead73ba] succeeded in 1.0017712819972076s: 12
[2024-01-28 00:14:28,834: INFO/MainProcess] Task maths.tasks.task_sum[9644ab07-1d64-448b-8335-37827a247ab2] received
[2024-01-28 00:14:28,835: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[8656febd-4662-4f9f-8d80-56b604e6144a] succeeded in 1.0038902780215722s: 12
[2024-01-28 00:14:28,847: INFO/MainProcess] Task maths.tasks.task_sum[0fdc4bff-71ca-4679-b3e8-d329e9e75575] received
[2024-01-28 00:14:29,612: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[0c97c98f-f01a-4445-aa18-21e88e628971] succeeded in 1.0021464340097737s: 12
[2024-01-28 00:14:29,618: INFO/MainProcess] Task maths.tasks.task_sum[1526c6f0-efee-4ed4-8d20-10505d2784b8] received
[2024-01-28 00:14:29,701: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[9410768c-d257-49e4-85e8-bf3448ec16ce] succeeded in 1.0107824410079047s: 12
[2024-01-28 00:14:29,709: INFO/MainProcess] Task maths.tasks.task_sum[4725b57c-33c2-4e4f-a5f9-1c8a693374a6] received
[2024-01-28 00:14:29,836: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[6ef60e7f-4e64-4370-98eb-7819c845d93c] succeeded in 1.0052865580073558s: 12
[2024-01-28 00:14:29,850: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[bd86888f-c17d-4b24-9913-119306f2f120] succeeded in 1.0086806809995323s: 12
[2024-01-28 00:14:29,877: INFO/MainProcess] Task maths.tasks.task_sum[e5cc79f3-63d2-4a84-8833-46451cf66201] received
[2024-01-28 00:14:29,914: INFO/MainProcess] Task maths.tasks.task_sum[33c9cecf-7583-4b02-b372-212746edbc73] received
[2024-01-28 00:14:30,617: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[17349874-3969-41aa-a88e-de33ae28025d] succeeded in 1.00190530801774s: 12
[2024-01-28 00:14:30,621: INFO/MainProcess] Task maths.tasks.task_sum[bfea8a40-d34f-4cdf-804e-2192b15787fe] received
[2024-01-28 00:14:30,706: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[f8ede4b6-ccc7-4cf9-8580-53a6ba8c3b99] succeeded in 1.0009922619792633s: 12
[2024-01-28 00:14:30,710: INFO/MainProcess] Task maths.tasks.task_sum[8d706092-1af8-4fba-9c65-522bb1c1f539] received
[2024-01-28 00:14:30,855: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[6472f0a9-6504-4199-81b6-332075345a7a] succeeded in 1.0018674329912756s: 12
[2024-01-28 00:14:30,860: INFO/MainProcess] Task maths.tasks.task_sum[23d5a6fe-92bb-49d3-8623-4ea716b6075d] received
[2024-01-28 00:14:30,887: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[ee20583f-25f6-4401-a750-404ca46bf722] succeeded in 1.0019550540018827s: 12
[2024-01-28 00:14:30,893: INFO/MainProcess] Task maths.tasks.task_sum[f58b0a90-687f-4771-ad7e-775eb59634d8] received
[2024-01-28 00:14:31,625: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[15829dce-ba0b-4587-8497-d04320273f54] succeeded in 1.0055975999857765s: 12
[2024-01-28 00:14:31,651: INFO/MainProcess] Task maths.tasks.task_sum[9d6a2b73-85b8-465a-9fae-8dc67e9b86ff] received
[2024-01-28 00:14:31,710: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[bd10892a-4e26-42e6-bd05-bbfa4f237419] succeeded in 1.002375732990913s: 12
[2024-01-28 00:14:31,725: INFO/MainProcess] Task maths.tasks.task_sum[9f0dca07-3f88-4fdf-bcee-58af089430e0] received
[2024-01-28 00:14:31,861: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[9101357c-e2b5-4705-8dfe-3b012471604b] succeeded in 1.0035911859886255s: 12
[2024-01-28 00:14:31,879: INFO/MainProcess] Task maths.tasks.task_sum[03089b96-886f-4ff4-928e-a4ef57d7667a] received
[2024-01-28 00:14:31,892: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[9b943ba8-0511-400c-bd64-41814925b5a7] succeeded in 1.0016523890080862s: 12
[2024-01-28 00:14:31,900: INFO/MainProcess] Task maths.tasks.task_sum[a8461f4e-8929-45f0-81fc-e705a5e2284f] received
[2024-01-28 00:14:32,644: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[c4379c4a-4c38-43fb-b092-23e8e7eb58df] succeeded in 1.0056026699894574s: 12
[2024-01-28 00:14:32,670: INFO/MainProcess] Task maths.tasks.task_sum[9044b59a-11bd-42cb-9910-59dcafcfdcac] received
[2024-01-28 00:14:32,721: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[85bf4870-17ad-496e-b89b-a1404f49b2dc] succeeded in 1.0023262350005098s: 12
[2024-01-28 00:14:32,736: INFO/MainProcess] Task maths.tasks.task_sum[f0f6f091-0583-46d6-a3a4-6d8e61b4b2b2] received
[2024-01-28 00:14:32,868: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[bab665bf-c772-4366-a361-eef9f0dab668] succeeded in 1.0015150399995036s: 12
[2024-01-28 00:14:32,874: INFO/MainProcess] Task maths.tasks.task_sum[bf7c52c8-d0f6-488e-a46f-8627545e3663] received
[2024-01-28 00:14:32,896: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[199adb6d-ab31-43c8-b40c-ef4c30c36b8c] succeeded in 1.0011103749857284s: 12
[2024-01-28 00:14:32,901: INFO/MainProcess] Task maths.tasks.task_sum[3df0e88b-87b2-470c-b81f-860dc0af9c1a] received
[2024-01-28 00:14:33,657: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[86c47ba2-35bd-4eb0-b66c-2a6d993b0f3d] succeeded in 1.001461218984332s: 12
[2024-01-28 00:14:33,727: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[6e9e904b-f67b-4d3e-8b72-1ae70f3d1ebe] succeeded in 1.0011185879993718s: 12
[2024-01-28 00:14:33,874: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[9644ab07-1d64-448b-8335-37827a247ab2] succeeded in 1.0026266350178048s: 12
[2024-01-28 00:14:33,901: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[0fdc4bff-71ca-4679-b3e8-d329e9e75575] succeeded in 1.002257999003632s: 12
[2024-01-28 00:14:34,660: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[1526c6f0-efee-4ed4-8d20-10505d2784b8] succeeded in 1.0012175550218672s: 12
[2024-01-28 00:14:34,730: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[4725b57c-33c2-4e4f-a5f9-1c8a693374a6] succeeded in 1.0011755379964598s: 12
[2024-01-28 00:14:34,881: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[e5cc79f3-63d2-4a84-8833-46451cf66201] succeeded in 1.002149253996322s: 12
[2024-01-28 00:14:34,907: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[33c9cecf-7583-4b02-b372-212746edbc73] succeeded in 1.0011178440181538s: 12
[2024-01-28 00:14:35,663: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[bfea8a40-d34f-4cdf-804e-2192b15787fe] succeeded in 1.0013454069849104s: 12
[2024-01-28 00:14:35,747: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[8d706092-1af8-4fba-9c65-522bb1c1f539] succeeded in 1.0062872970011085s: 12
[2024-01-28 00:14:35,885: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[23d5a6fe-92bb-49d3-8623-4ea716b6075d] succeeded in 1.0013416110014077s: 12
[2024-01-28 00:14:35,911: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[f58b0a90-687f-4771-ad7e-775eb59634d8] succeeded in 1.0014793899899814s: 12
[2024-01-28 00:14:36,670: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[9d6a2b73-85b8-465a-9fae-8dc67e9b86ff] succeeded in 1.0044374580029398s: 12
[2024-01-28 00:14:36,769: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[9f0dca07-3f88-4fdf-bcee-58af089430e0] succeeded in 1.0061901390145067s: 12
[2024-01-28 00:14:36,888: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[03089b96-886f-4ff4-928e-a4ef57d7667a] succeeded in 1.0010797760041896s: 12
[2024-01-28 00:14:36,914: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[a8461f4e-8929-45f0-81fc-e705a5e2284f] succeeded in 1.0010389010130893s: 12
[2024-01-28 00:14:37,682: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[9044b59a-11bd-42cb-9910-59dcafcfdcac] succeeded in 1.002905486006057s: 12
[2024-01-28 00:14:37,778: INFO/ForkPoolWorker-3] Task maths.tasks.task_sum[f0f6f091-0583-46d6-a3a4-6d8e61b4b2b2] succeeded in 1.00185542597319s: 12
[2024-01-28 00:14:37,892: INFO/ForkPoolWorker-2] Task maths.tasks.task_sum[bf7c52c8-d0f6-488e-a46f-8627545e3663] succeeded in 1.0013154420012143s: 12
[2024-01-28 00:14:37,918: INFO/ForkPoolWorker-4] Task maths.tasks.task_sum[3df0e88b-87b2-470c-b81f-860dc0af9c1a] succeeded in 1.0015528530057054s: 12
[2024-01-28 02:09:10,234: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:09:10,242: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 02:09:10,244: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:09:10,246: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 02:09:11,256: INFO/MainProcess] mingle: all alone
[2024-01-28 02:09:11,276: INFO/MainProcess] celery@e91e60a837f1 ready.
[2024-01-28 02:09:14,432: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 02:10:28,439: INFO/MainProcess] Task maths.tasks.task_sum[0b1e5910-6ee8-4937-a4b8-c890e0982b35] received
[2024-01-28 02:10:29,460: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[0b1e5910-6ee8-4937-a4b8-c890e0982b35] succeeded in 1.0183899299881887s: 12
[2024-01-28 02:11:48,702: INFO/MainProcess] Task maths.tasks.task_sum[5e621c00-3b22-45bf-b629-f43b6db7cc16] received
[2024-01-28 02:11:49,706: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[5e621c00-3b22-45bf-b629-f43b6db7cc16] succeeded in 1.0020302410121076s: 101
[2024-01-28 02:14:31,280: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:14:31,286: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 02:14:31,288: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:14:31,290: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 02:14:32,299: INFO/MainProcess] mingle: all alone
[2024-01-28 02:14:32,314: INFO/MainProcess] celery@84604942bb71 ready.
[2024-01-28 02:14:35,962: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 02:14:52,653: INFO/MainProcess] Task maths.tasks.task_sum[882e4e63-8c74-4fb5-a5e6-dd96dc9a995c] received
[2024-01-28 02:14:53,658: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[882e4e63-8c74-4fb5-a5e6-dd96dc9a995c] succeeded in 1.0033090359938797s: 101
[2024-01-28 02:15:13,109: INFO/MainProcess] Task maths.tasks.task_sum[1ae77e50-6f5d-48f4-8eae-2e78f8d4592f] received
[2024-01-28 02:15:14,121: INFO/ForkPoolWorker-1] Task maths.tasks.task_sum[1ae77e50-6f5d-48f4-8eae-2e78f8d4592f] succeeded in 1.005634519009618s: 12
[2024-01-28 02:30:56,337: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:30:56,346: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 02:30:56,347: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:30:56,351: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 02:30:57,360: INFO/MainProcess] mingle: all alone
[2024-01-28 02:30:57,373: INFO/MainProcess] celery@76a1d1192f38 ready.
[2024-01-28 02:31:01,112: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 02:40:38,246: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:40:38,252: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 02:40:38,254: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:40:38,256: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 02:40:39,266: INFO/MainProcess] mingle: all alone
[2024-01-28 02:40:39,280: INFO/MainProcess] celery@66b0e6300ac9 ready.
[2024-01-28 02:40:42,725: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 02:43:48,984: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:43:48,990: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 02:43:48,991: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:43:48,993: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 02:43:50,002: INFO/MainProcess] mingle: all alone
[2024-01-28 02:43:50,019: INFO/MainProcess] celery@fdce8fa6d75e ready.
[2024-01-28 02:43:53,599: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 02:52:45,541: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:52:45,547: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 02:52:45,548: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:52:45,551: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 02:52:46,560: INFO/MainProcess] mingle: all alone
[2024-01-28 02:52:46,574: INFO/MainProcess] celery@78bd971de628 ready.
[2024-01-28 02:52:50,073: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 02:53:25,320: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:53:25,327: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 02:53:25,329: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 02:53:25,331: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 02:53:26,342: INFO/MainProcess] mingle: all alone
[2024-01-28 02:53:26,356: INFO/MainProcess] celery@995ad0e9d3ef ready.
[2024-01-28 02:53:29,926: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 02:54:00,010: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': 'bc8369c9-dccb-463e-85a2-2058bf02ad39', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'bc8369c9-dccb-463e-85a2-2058bf02ad39', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 02:55:00,007: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '53b1c314-7a8e-4a4d-b89c-dfe32dc0ff84', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '53b1c314-7a8e-4a4d-b89c-dfe32dc0ff84', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 02:56:00,021: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '0a8e2d74-691f-46e3-8fc2-4df1142cee1a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '0a8e2d74-691f-46e3-8fc2-4df1142cee1a', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 02:57:00,016: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '39a45ca7-4b01-43cf-ae07-02166a4c0dba', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '39a45ca7-4b01-43cf-ae07-02166a4c0dba', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 02:58:00,002: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '257c86a5-1622-4068-b40a-afb83506a760', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '257c86a5-1622-4068-b40a-afb83506a760', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 02:59:00,018: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '726d2c5f-23ce-4a7f-91af-bd17eb8aee68', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '726d2c5f-23ce-4a7f-91af-bd17eb8aee68', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:00:00,007: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': 'f6af663f-1590-4435-864d-75c3d5bc4334', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f6af663f-1590-4435-864d-75c3d5bc4334', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:01:00,018: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '31c01b23-4d2f-4df5-9555-a68136db2ac2', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '31c01b23-4d2f-4df5-9555-a68136db2ac2', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:02:00,017: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': 'c76bf0e8-8bf1-44a8-9893-6ae3d1eefc74', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'c76bf0e8-8bf1-44a8-9893-6ae3d1eefc74', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:03:00,016: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': 'ae610a07-4414-48f0-9452-c886400537c3', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'ae610a07-4414-48f0-9452-c886400537c3', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:04:00,027: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '6d2fc48c-062a-4513-8156-dafd67935507', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '6d2fc48c-062a-4513-8156-dafd67935507', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:05:00,017: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '8e72bb82-35a8-4023-9462-470561ab2521', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '8e72bb82-35a8-4023-9462-470561ab2521', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:06:00,045: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': 'f019ab41-406b-45ce-ab97-b50d21a4f20d', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f019ab41-406b-45ce-ab97-b50d21a4f20d', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@144c43379355', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:07:14,168: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 03:07:14,176: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 03:07:14,178: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 03:07:14,181: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 03:07:15,192: INFO/MainProcess] mingle: all alone
[2024-01-28 03:07:15,208: INFO/MainProcess] celery@b6eb8b4b8547 ready.
[2024-01-28 03:07:15,620: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': 'ab1a4a9e-79a4-4f31-bc91-f2a0a50116b8', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'ab1a4a9e-79a4-4f31-bc91-f2a0a50116b8', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@4a61d860fb60', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:07:18,641: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 03:08:00,023: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '0e286c85-fadd-4c29-9a2a-d5d2985bcc3c', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '0e286c85-fadd-4c29-9a2a-d5d2985bcc3c', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@4a61d860fb60', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:09:00,003: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': '34d15c08-c899-4a71-ab52-6a9769ea09a7', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '34d15c08-c899-4a71-ab52-6a9769ea09a7', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@4a61d860fb60', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:18:10,603: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 03:18:10,620: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-28 03:18:10,625: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 03:18:10,629: INFO/MainProcess] mingle: searching for neighbors
[2024-01-28 03:18:11,645: INFO/MainProcess] mingle: all alone
[2024-01-28 03:18:11,661: INFO/MainProcess] celery@96e7a41f98d4 ready.
[2024-01-28 03:18:12,091: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.sample_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.sample_task', 'id': 'fbfb47fc-4e00-47d7-b69e-1f4275be4231', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'fbfb47fc-4e00-47d7-b69e-1f4275be4231', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.sample_task'
[2024-01-28 03:18:12,097: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '167e9f57-33e0-4923-9f0b-69d21111d164', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '167e9f57-33e0-4923-9f0b-69d21111d164', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:12,665: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '728eeb8a-f555-42dd-a364-a7b8916cfa0f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '728eeb8a-f555-42dd-a364-a7b8916cfa0f', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:13,665: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'ec036d45-aa1f-479b-9f4a-091d70d3a196', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'ec036d45-aa1f-479b-9f4a-091d70d3a196', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:14,665: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '513f90ca-b49f-4e15-8650-eb1da53254db', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '513f90ca-b49f-4e15-8650-eb1da53254db', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:14,992: INFO/MainProcess] Events of group {task} enabled by remote.
[2024-01-28 03:18:15,678: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'ff6edfd8-cbfb-4731-8f81-24db53662627', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'ff6edfd8-cbfb-4731-8f81-24db53662627', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:16,677: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '41c344bc-faf1-4f1d-aadf-18d2baafe09b', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '41c344bc-faf1-4f1d-aadf-18d2baafe09b', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:17,680: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '9c7ba798-b912-430e-99a8-8f8e8d3aaae4', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '9c7ba798-b912-430e-99a8-8f8e8d3aaae4', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:18,677: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'f9d2f3df-1310-43a9-a2af-b5bbeb910004', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f9d2f3df-1310-43a9-a2af-b5bbeb910004', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:19,685: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '8b206399-61e2-42a7-8315-bed1affb43be', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '8b206399-61e2-42a7-8315-bed1affb43be', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:20,669: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'acbd31cf-3f75-41e2-9265-3ff717be4e27', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'acbd31cf-3f75-41e2-9265-3ff717be4e27', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:21,673: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'e855f088-a321-4c10-b556-8a472ed851f7', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'e855f088-a321-4c10-b556-8a472ed851f7', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:22,679: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'b6d9e4ad-2533-4611-a55e-22bc931f0975', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'b6d9e4ad-2533-4611-a55e-22bc931f0975', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:23,669: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '0dc2c27e-b916-4b0e-8dbd-28fef286f593', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '0dc2c27e-b916-4b0e-8dbd-28fef286f593', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:24,669: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'fb6f722e-7028-4949-9197-31f0133e46ee', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'fb6f722e-7028-4949-9197-31f0133e46ee', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:25,679: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '26b062fb-1861-445e-8bf5-c3f65569b746', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '26b062fb-1861-445e-8bf5-c3f65569b746', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:26,670: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'c2d06fce-ac14-4ab0-bbbd-a39b5533f914', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'c2d06fce-ac14-4ab0-bbbd-a39b5533f914', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:27,682: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '5503a7fb-54e3-4522-b056-2ebeae6994ec', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '5503a7fb-54e3-4522-b056-2ebeae6994ec', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:28,670: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '856f0922-e79a-4ce3-90af-9137ee7c89b7', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '856f0922-e79a-4ce3-90af-9137ee7c89b7', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:29,670: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'abc9f0ae-0397-4404-9782-6c0b051c46d3', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'abc9f0ae-0397-4404-9782-6c0b051c46d3', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:30,680: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '614bebb1-ea3f-43f1-ba5c-452bc6cec382', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '614bebb1-ea3f-43f1-ba5c-452bc6cec382', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:31,683: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'bc2d5fbe-7981-4dbe-89a9-59130c54c47e', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'bc2d5fbe-7981-4dbe-89a9-59130c54c47e', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:32,683: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'e0ad4a75-704f-474e-af34-549d4f74498c', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'e0ad4a75-704f-474e-af34-549d4f74498c', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:33,683: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '219eb192-9694-4daf-9021-b62ec32a9413', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '219eb192-9694-4daf-9021-b62ec32a9413', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:34,685: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '12fd8622-13de-417e-87fe-051cd6f25c6c', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '12fd8622-13de-417e-87fe-051cd6f25c6c', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:35,685: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '5285974d-9497-4a33-9fe4-764a799a2f80', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '5285974d-9497-4a33-9fe4-764a799a2f80', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:36,684: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '429292c6-5619-4080-ac94-899a31c44059', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '429292c6-5619-4080-ac94-899a31c44059', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:37,684: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '0878a80e-d3ca-49ce-aa46-0ae69f6764a9', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '0878a80e-d3ca-49ce-aa46-0ae69f6764a9', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:38,686: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '2ae360a2-3973-467d-ad87-5da6e0158d17', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '2ae360a2-3973-467d-ad87-5da6e0158d17', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:39,679: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '7d2c2450-d00f-44be-af15-3b17a6e38e93', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '7d2c2450-d00f-44be-af15-3b17a6e38e93', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:40,678: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'af24de52-8a27-4256-80d0-b997fd81d36e', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'af24de52-8a27-4256-80d0-b997fd81d36e', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:41,686: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '9bbc70f5-b798-4f82-baf9-31e2f095612b', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '9bbc70f5-b798-4f82-baf9-31e2f095612b', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:42,686: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'ef9ffc3f-928d-49eb-a852-d0ffa2c87a27', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'ef9ffc3f-928d-49eb-a852-d0ffa2c87a27', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:43,687: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '82238dc7-1637-4b25-8f48-63b9ac4cb0fd', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '82238dc7-1637-4b25-8f48-63b9ac4cb0fd', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:44,686: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'ca423b10-3297-4f78-9d1c-278830a9181f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'ca423b10-3297-4f78-9d1c-278830a9181f', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:45,677: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': '866d06c8-f1d5-4c67-82ed-217abaadd798', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '866d06c8-f1d5-4c67-82ed-217abaadd798', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:46,687: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'a6bbc041-4035-4fa7-8cf0-d5549e15daef', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'a6bbc041-4035-4fa7-8cf0-d5549e15daef', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:47,687: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'b7cd348c-248c-45fe-9ad0-3b59b91297ae', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'b7cd348c-248c-45fe-9ad0-3b59b91297ae', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
[2024-01-28 03:18:48,700: ERROR/MainProcess] Received unregistered task of type 'backend.tasks.just_print'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'backend.tasks.just_print', 'id': 'a817e722-6f83-4dcf-8702-26c50753b93f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'a817e722-6f83-4dcf-8702-26c50753b93f', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@ce27befd6d0d', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'backend.tasks.just_print'
